module.exports = {
  devServer:{
    open:true,
    host:'localhost',
    port:8080,
    proxy:{
      '/api':{
        target:'http://mall-pre.springboot.cn',
        changeOrigin:true,
        pathRewrite:{
          '/api':''
        }
      }
    }
  },
  productionSourceMap:true,
  //删除预加载
  chainWebpack:(config)=>{
    config.plugins.delete('prefetch');
  }
}